# Generated by Django 4.0.3 on 2022-03-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_language_alter_resource_database_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='resource',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.language'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.database'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.framework'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.technology'),
        ),
    ]
