# Generated by Django 4.0.3 on 2022-03-09 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_database_framework_technology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='database',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='journal.database'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='framework',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='journal.framework'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='language',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='journal.language'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='technology',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='journal.technology'),
        ),
    ]
